// Host tests for the receive path: LineAssembler + json extractors + command handling
// (prompt 23 Stage 1, spec SENT-026/107/160).
//
// The literal frames below were generated by the Pi's PYTHON codec
// (rosbottiNG sentlink/codec.py) on 2026-07-28 — the cross-validation rule: both ends
// must chew IDENTICAL bytes. If a vector fails here, the two codecs have diverged.
#include <string.h>

#include <unity.h>

#include "commands.h"
#include "sentlink.h"
#include "wire.h"

using namespace sentlink;

// ---- Python-codec vectors (do not edit by hand — regenerate from sentlink/codec.py) ----
static const char* PY_C_PING      = "1C7|{\"cmd\":\"ping\"}|F135\n";
static const char* PY_C_DESCRIBE  = "1C8|{\"cmd\":\"describe\"}|22FE\n";
static const char* PY_C_SETCLOCK  = "1C9|{\"cmd\":\"set_clock\",\"epoch_s\":1785200000.25}|BDEB\n";
static const char* PY_R_PIACKSB   = "1R55|{\"ack\":42}|E939\n";
static const char* PY_N_PINACKS   = "1N56|{\"nack\":42,\"reason\":\"crc\"}|C09D\n";
// What the PYTHON codec produces for frames WE will emit — our encode must match byte-for-byte:
static const char* PY_R_PINGRESP  = "1R3|{\"ack\":7,\"pong\":1}|B401\n";
static const char* PY_H_CONFORM   = "1H2|{\"up_ms\":12345,\"fw\":\"0.2.0\",\"proto\":1}|B7AB\n";

// ---------------------------------------------------------------- LineAssembler
static void test_assembler_splits_lines(void) {
  LineAssembler a;
  const char* stream = "1C7|{\"cmd\":\"ping\"}|F135\nHB noise\n";
  int lines = 0;
  char first[64] = {0};
  for (const char* p = stream; *p; p++) {
    if (a.feed(*p)) {
      lines++;
      if (lines == 1) strncpy(first, a.line(), sizeof(first) - 1);
    }
  }
  TEST_ASSERT_EQUAL_INT(2, lines);
  TEST_ASSERT_EQUAL_STRING("1C7|{\"cmd\":\"ping\"}|F135", first);
}

static void test_assembler_bounded_overflow(void) {
  LineAssembler a;
  for (size_t i = 0; i < MAX_FRAME + 50; i++) TEST_ASSERT_FALSE(a.feed('x'));
  TEST_ASSERT_FALSE(a.feed('\n'));            // over-long line dropped WHOLE, not delivered
  TEST_ASSERT_EQUAL_UINT32(1, a.overflows());
  TEST_ASSERT_TRUE(a.feed('o') || true);      // and the next line still works
  TEST_ASSERT_TRUE(a.feed('\n'));
  TEST_ASSERT_EQUAL_STRING("o", a.line());
}

// ---------------------------------------------------------------- json extractors
static void test_json_extractors(void) {
  uint32_t u = 0;
  double d = 0;
  char s[16];
  const char* p = "{\"ack\":42,\"epoch_s\":1785200000.25,\"cmd\":\"ping\",\"backlog\":0}";
  TEST_ASSERT_TRUE(json_uint(p, "ack", u));
  TEST_ASSERT_EQUAL_UINT32(42, u);
  TEST_ASSERT_TRUE(json_double(p, "epoch_s", d));
  TEST_ASSERT_TRUE(d > 1785199999.0 && d < 1785200001.0);
  TEST_ASSERT_TRUE(json_str(p, "cmd", s, sizeof(s)));
  TEST_ASSERT_EQUAL_STRING("ping", s);
  TEST_ASSERT_FALSE(json_uint(p, "absent", u));
  TEST_ASSERT_FALSE(json_str(p, "ack", s, sizeof(s)));   // number is not a string
  // "ck" must not match inside "ack"/"backlog" (quoted-key rule)
  TEST_ASSERT_FALSE(json_uint(p, "ck", u));
}

// ---------------------------------------------------------------- cross-validation: decode
static void test_decode_python_command_frames(void) {
  char buf[MAX_FRAME];
  Frame f;

  strncpy(buf, PY_C_PING, sizeof(buf));
  TEST_ASSERT_TRUE(decode(buf, strlen(buf), f));
  TEST_ASSERT_TRUE(f.crc_ok);
  TEST_ASSERT_EQUAL_CHAR((char)Type::Command, (char)f.type);
  TEST_ASSERT_EQUAL_UINT32(7, f.seq);
  TEST_ASSERT_EQUAL_STRING("{\"cmd\":\"ping\"}", f.payload);

  strncpy(buf, PY_R_PIACKSB, sizeof(buf));
  TEST_ASSERT_TRUE(decode(buf, strlen(buf), f));
  TEST_ASSERT_TRUE(f.crc_ok);
  uint32_t target = 0;
  TEST_ASSERT_TRUE(json_uint(f.payload, "ack", target));
  TEST_ASSERT_EQUAL_UINT32(42, target);      // the seq the transport must clear

  strncpy(buf, PY_N_PINACKS, sizeof(buf));
  TEST_ASSERT_TRUE(decode(buf, strlen(buf), f));
  TEST_ASSERT_TRUE(json_uint(f.payload, "nack", target));
  TEST_ASSERT_EQUAL_UINT32(42, target);
}

// ---------------------------------------------------------------- cross-validation: encode
static void test_encode_matches_python_codec(void) {
  char buf[MAX_FRAME];
  size_t n = encode(buf, sizeof(buf), Type::Ack, 3, "{\"ack\":7,\"pong\":1}");
  TEST_ASSERT_TRUE(n > 0);
  TEST_ASSERT_EQUAL_STRING(PY_R_PINGRESP, buf);

  n = encode(buf, sizeof(buf), Type::Heartbeat, 2, "{\"up_ms\":12345,\"fw\":\"0.2.0\",\"proto\":1}");
  TEST_ASSERT_TRUE(n > 0);
  TEST_ASSERT_EQUAL_STRING(PY_H_CONFORM, buf);
}

// ---------------------------------------------------------------- commands
static void run_cmd(const char* frame_literal, CmdCtx& ctx, char* out, size_t cap, bool& is_ack) {
  char buf[MAX_FRAME];
  Frame f;
  strncpy(buf, frame_literal, sizeof(buf));
  TEST_ASSERT_TRUE(decode(buf, strlen(buf), f));
  TEST_ASSERT_TRUE(f.crc_ok);
  const size_t n = handle_command(f.payload, f.seq, 5000, ctx, out, cap, is_ack);
  TEST_ASSERT_TRUE(n > 0);
}

static void test_command_ping(void) {
  CmdCtx ctx;
  char out[MAX_PAYLOAD];
  bool is_ack = false;
  run_cmd(PY_C_PING, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_TRUE(is_ack);
  TEST_ASSERT_EQUAL_STRING("{\"ack\":7,\"pong\":1}", out);   // exactly what the Pi parses
}

static void test_command_describe_roster(void) {
  CmdCtx ctx;
  char out[MAX_PAYLOAD];
  bool is_ack = false;
  run_cmd(PY_C_DESCRIBE, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_TRUE(is_ack);
  uint32_t target = 0;
  TEST_ASSERT_TRUE(json_uint(out, "ack", target));
  TEST_ASSERT_EQUAL_UINT32(8, target);
  TEST_ASSERT_NOT_NULL(strstr(out, "\"fw\":\"0.2.0\""));
  TEST_ASSERT_NOT_NULL(strstr(out, "\"proto\":1"));
  TEST_ASSERT_NOT_NULL(strstr(out, "\"range\""));            // the ultrasonic is in the roster
}

static void test_command_set_clock_and_idempotence(void) {
  CmdCtx ctx;
  char out[MAX_PAYLOAD];
  bool is_ack = false;
  run_cmd(PY_C_SETCLOCK, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_TRUE(is_ack);
  TEST_ASSERT_TRUE(ctx.clock_set);
  TEST_ASSERT_TRUE(ctx.epoch_s > 1785199999.0);
  TEST_ASSERT_EQUAL_UINT32(5000, ctx.epoch_at_ms);
  // Idempotent: the bridge retries with fresh seqs — same command twice must be harmless.
  run_cmd(PY_C_SETCLOCK, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_TRUE(is_ack);
  TEST_ASSERT_TRUE(ctx.clock_set);
}

static void test_command_unknown_nacks(void) {
  CmdCtx ctx;
  char out[MAX_PAYLOAD];
  bool is_ack = true;
  const size_t n = handle_command("{\"cmd\":\"frobnicate\"}", 11, 0, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_TRUE(n > 0);
  TEST_ASSERT_FALSE(is_ack);
  TEST_ASSERT_EQUAL_STRING("{\"nack\":11,\"err\":\"unknown_cmd\"}", out);
}

static void test_command_reboot_defers(void) {
  CmdCtx ctx;
  char out[MAX_PAYLOAD];
  bool is_ack = false;
  handle_command("{\"cmd\":\"reboot\"}", 12, 0, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_TRUE(is_ack);
  TEST_ASSERT_TRUE(ctx.want_reboot);        // flag only — the loop reboots AFTER the R is out
}

static void test_command_sensors_toggle(void) {
  CmdCtx ctx;
  char out[MAX_PAYLOAD];
  bool is_ack = false;
  handle_command("{\"cmd\":\"sensors_off\"}", 13, 0, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_FALSE(ctx.sensors_on);
  handle_command("{\"cmd\":\"sensors_on\"}", 14, 0, ctx, out, sizeof(out), is_ack);
  TEST_ASSERT_TRUE(ctx.sensors_on);
}

int main(int, char**) {
  UNITY_BEGIN();
  RUN_TEST(test_assembler_splits_lines);
  RUN_TEST(test_assembler_bounded_overflow);
  RUN_TEST(test_json_extractors);
  RUN_TEST(test_decode_python_command_frames);
  RUN_TEST(test_encode_matches_python_codec);
  RUN_TEST(test_command_ping);
  RUN_TEST(test_command_describe_roster);
  RUN_TEST(test_command_set_clock_and_idempotence);
  RUN_TEST(test_command_unknown_nacks);
  RUN_TEST(test_command_reboot_defers);
  RUN_TEST(test_command_sensors_toggle);
  return UNITY_END();
}
